### PR TITLE
feat(rich-text): improve (type) safety

### PR DESCRIPTION
**Pull request by jeysal**

### CODE REVIEW

**Comment by jeysal** [comment]
@fampinheiro this is the rough direction of my attempt to fix the safety issues that the types are pointing at for your eyes. obviously not final either, this will have to grow as we support more tags etc.

**Comment by jeysal** [comment]
Won't focus on this for now but will probably occasionally push something here when I need a break from my main work ;D

**Comment by fampinheiro** [comment]
It looks like an improvements, do we want to break hard on lack of `id`? The jump it's a nice to have, don't want the page to break on slug misbehaving.

**Comment by jeysal** [comment]
> It looks like an improvements, do we want to break hard on lack of `id`? The jump it's a nice to have, don't want the page to break on slug misbehaving.

My understanding is that `rehype-slug` is used to generate an `id` for *every* `<h*>` based on its text content, so the `id` not being a `string` (but e.g. `undefined`) would be a hypothetical case that should never occur at runtime, thus warranting an assertion.

**Comment by jeysal** [comment]
I see, only with `toc` prop

**Comment by jeysal** [comment]
The typings for `rehype-react` are indeed garbage. This will need a cast, but I think what I've done now  is what we need: Converting from props that rehype can normally pass to a `p / h1 / a / ...` to props that we can pass to our `Paragraph / Headline2 / Link / ...`. It's tested, and because I think I did the *right* cast the tests now manage to cover all cases that could happen with rehype in reality.

**Review by fampinheiro — APPROVED** [review]

**Comment by jeysal** [comment]
when deployed should check that terms page still works, cannot test locally atm due to a CORS config problem

**Comment by jeysal** [comment]
seems to work https://209.hub.asap.science/privacy-policy

**Pull request merged**
