### PR TITLE
build: use wildcard versions for workspace packages

### PR DESCRIPTION
**Pull request by jeysal**

### CODE REVIEW

**Comment by jeysal** [comment]
Apparently this is a thing, learned from a random PR on Jest. Much simpler, and while totally not relevant here also learned that it's better in some wild sub-workspaces setups.

**Review by fampinheiro — APPROVED** [review]
What is the reasoning behind this change? Why is a wildcard better than specifying the path to the package.

**Comment by jeysal** [comment]
For us it's literally just removing the overhead, and makes it easier to change directory structure because it now just looks at package names.
Not relevant for us: It helps when embedding a workspace in another, because the path would no longer be correct from the workspace root https://github.com/facebook/jest/issues/10761

**Comment by fampinheiro** [comment]
Thanks. I was more interested in the second part of the explanation :+1:

**Pull request merged**
