### PR TITLE
CRN-716 make url optional for lab resources

### PR DESCRIPTION
**Pull request by marot**
https://asaphub.atlassian.net/browse/CRN-716

### CODE REVIEW

**Review by niezgoda — APPROVED** [review]

**Review by kmaid — CHANGES_REQUESTED** [review]
What about backend validation? Also I think we have some defaults in TeamOutput and a typed api response that might need to be updated

**Comment by niezgoda** [comment]
I have assumed that on the backend this field is optional @kmaid

**Comment by marot** [comment]
@kmaid The field is not optional, but we are sending an empty string. There is no validation on the backend that the URL starts with http or anything similar - it just needs a string (and it can be empty afair)

**Comment by marot** [comment]
@kmaid The defaults in TeamOutput.tsx have no effect because they are only applied for parts that are not implemented.

**Review by kmaid — APPROVED** [review]

**Comment by niezgoda** [comment]
I have approved this, but.
We shouldn't send empty string.
This field should be optional.
The migration shall be written to replace all empty strings with undefined / null.

**Review by niezgoda — CHANGES_REQUESTED** [review]
I have approved this, but.
We shouldn't send empty string.
This field should be optional.
The migration shall be written to replace all empty strings with undefined / null.

**Comment by marot** [comment]
@niezgoda can you check again?

**Comment by marot** [comment]
I will re-create the PR because the gitlab env is broken

**Pull request closed without merging**
