### PR TITLE
feat: revert react-components bundle and keep things simple

### PR DESCRIPTION
**Pull request by fampinheiro**

### CODE REVIEW

**Comment by jeysal** [comment]
What's the problem this solves? :sweat_smile: because it does not seem simpler ^^

**Comment by fampinheiro** [comment]
The rendering automation of emails wasn't working. I spent a day trying to come up with an automated solution and couldn't find one. So this pull request was born, there is no automation creating the templates, just automation pushing them to aws.

**Comment by jeysal** [comment]
How did we generate the email previously?

**Comment by fampinheiro** [comment]
It worked on a subset of the components we had. Somewhere during the iterations of the components we introduced a rule that makes the bundled code throw an exception when loading it to inline the css styles.

**Pull request closed without merging**
